### ISSUE TITLE
Use CSS variables, consolidate all 'colors' in css

### ISSUE THREAD

**Issue by jackharrhy** [djkean/FoodForAll#17]
- ensure no colors are defined in javascript
- define all colors using CSS custom variables ( https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties )

```css
:root {
  --primary: blue;
  --secondary: yellow;
  --background: green;
}
```
^ example
- ensure everything in the css file is using the custom variables
